# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: emotion_analysis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'emotion_analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65motion_analysis.proto\x12\x07\x65motion\"\x1e\n\x0e\x45motionRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"+\n\x07\x45motion\x12\r\n\x05label\x18\x01 \x01(\t\x12\x11\n\tintensity\x18\x02 \x01(\x02\"G\n\x0f\x45motionResponse\x12\x10\n\x08\x64ominant\x18\x01 \x01(\t\x12\"\n\x08\x65motions\x18\x02 \x03(\x0b\x32\x10.emotion.Emotion2V\n\x0f\x45motionAnalyzer\x12\x43\n\x0e\x41nalyzeEmotion\x12\x17.emotion.EmotionRequest\x1a\x18.emotion.EmotionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emotion_analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMOTIONREQUEST']._serialized_start=35
  _globals['_EMOTIONREQUEST']._serialized_end=65
  _globals['_EMOTION']._serialized_start=67
  _globals['_EMOTION']._serialized_end=110
  _globals['_EMOTIONRESPONSE']._serialized_start=112
  _globals['_EMOTIONRESPONSE']._serialized_end=183
  _globals['_EMOTIONANALYZER']._serialized_start=185
  _globals['_EMOTIONANALYZER']._serialized_end=271
# @@protoc_insertion_point(module_scope)
